language: node_js

cache: yarn

node_js:
  - "stable"
  - "12"

sudo: false

script:
  - yarn test:ci

deploy:
  - provider: npm
    edge: true
    email: "devmonk@mediamonks.com"
    api_key: $NPM_TOKEN
    on:
      tags: true
      node: "stable"
    skip_cleanup: true
  - provider: npm
    edge: true
    email: "devmonk@mediamonks.com"
    api_key: $NPM_TOKEN
    on:
      branch: next
      tags: true
      node: "stable"
    skip_cleanup: true